import { Capacitor } from '@capacitor/core'
import { LocalNotifications } from '@capacitor/local-notifications'
import { segmentLabel } from '../constants/pomodoro'

// Fixed id per segment slot (0-7) — a re-schedule cleanly replaces whatever was pending
// at that slot rather than piling up duplicates.
const NOTIFICATION_BASE_ID = 1000

// Max importance ("Urgent" in Android's channel settings) makes this a heads-up
// notification — it pops over whatever's on screen and, on most phones, wakes the
// display even without the full-screen-intent permission a real alarm app would need.
// A channel's importance/sound are locked in at creation; res/raw/pomodoro_ring.wav
// (generated by scripts/generate-ring-wav.cjs) is a ~10s ring so it's easy to notice
// from across a room, rather than the usual one-shot notification blip.
const CHANNEL_ID = 'pomodoro-alerts'
let channelReady = null

async function ensureChannel() {
  if (!channelReady) {
    channelReady = LocalNotifications.createChannel({
      id: CHANNEL_ID,
      name: 'Pomodoro Alerts',
      description: 'Alerts when a Pomodoro session or break ends',
      importance: 5,
      visibility: 1,
      sound: 'pomodoro_ring.wav',
      vibration: true,
      lights: true,
    }).catch(() => {})
  }
  return channelReady
}

async function ensurePermission() {
  const current = await LocalNotifications.checkPermissions()
  if (current.display === 'granted') return true
  const requested = await LocalNotifications.requestPermissions()
  return requested.display === 'granted'
}

/**
 * Schedules one OS-level notification per remaining segment in the current pass
 * through the sequence (from `startIndex` through the end — not wrapping into a new
 * cycle, see PomodoroContext for why). These fire from the native OS even while the
 * WebView/JS is suspended, unlike the in-app chime. No-op outside a native build.
 */
export async function scheduleRemainingNotifications(sequence, startIndex, startEndAt) {
  if (!Capacitor.isNativePlatform()) return
  try {
    if (!(await ensurePermission())) return
    await ensureChannel()
    await cancelPomodoroNotifications(sequence.length)

    const notifications = []
    let endAt = startEndAt
    for (let i = startIndex; i < sequence.length; i++) {
      const nextIndex = i + 1 === sequence.length ? 0 : i + 1
      notifications.push({
        id: NOTIFICATION_BASE_ID + i,
        title: segmentLabel(sequence, nextIndex),
        body: 'Alpha Pomodoro',
        channelId: CHANNEL_ID,
        schedule: { at: new Date(endAt) },
      })
      if (nextIndex === 0) break // stop at the end of this pass, don't schedule into a new cycle
      endAt += sequence[nextIndex].minutes * 60 * 1000
    }

    if (notifications.length > 0) await LocalNotifications.schedule({ notifications })
  } catch {
    // Notifications unsupported/denied — silently skip; the foreground chime still works.
  }
}

/** Cancels every notification id this module may have scheduled. */
export async function cancelPomodoroNotifications(sequenceLength) {
  if (!Capacitor.isNativePlatform()) return
  try {
    const notifications = Array.from({ length: sequenceLength }, (_, i) => ({ id: NOTIFICATION_BASE_ID + i }))
    await LocalNotifications.cancel({ notifications })
  } catch {
    // Nothing pending, or unsupported — fine either way.
  }
}

/** Cancels the notifications for specific segment indices (already handled by an in-app chime). */
export async function cancelSegmentNotifications(indices) {
  if (!Capacitor.isNativePlatform() || indices.length === 0) return
  try {
    const notifications = indices.map((i) => ({ id: NOTIFICATION_BASE_ID + i }))
    await LocalNotifications.cancel({ notifications })
  } catch {
    // Fine either way.
  }
}
